### ISSUE TITLE
Frontend / Client should be inside a separate folder

### ISSUE THREAD

**Issue by toreylittlefield** [lorenzojkrl/ecommerce-group-project#5]
@EugeneGohh Front / Client should be inside a separate folder not nested inside of the backend / server folder. 
- there should be one front-end (or client) and one back-end (or server) project directories. I guess they would probably share one parent directory folder i.e. "project-folder"
- This separation is necessary because for some reasons I am aware of but the biggest reason is the package.json and "build" (for production)  will not work correctly or have conflicts. Not a great explanation but that's the gist of it.

Example from Stackoverflow:
**Client Folder**
```
- /client 
-- /src
...
-- index.js
-- registerServiceWorker.js
- .gitignore
- package-lock.json
- package.json
```

**Server Folder**
```
- /server
- /models
-- item.js
- /node.modules
-- ...
- server.js
- package-lock.json
- package.json
```

**Comment by EugeneGohh** [comment]
Got it thanks. Found this [thread](https://stackoverflow.com/questions/51126472/how-to-organise-file-structure-of-backend-and-frontend-in-mern) from StackOverflow you're talking about. The file structure looks clean now.

**Comment by toreylittlefield** [comment]
### closed first request

We're closing the first pull request and trying again from Eugene's local.
