### ISSUE TITLE
Landing Page Containers & Navbar

### ISSUE THREAD

**Issue by toreylittlefield** [lorenzojkrl/ecommerce-group-project#6]
@toreylittlefield Torey - the last 3 containers on landing page
@EugeneGohh Eugene - navbar and the 2 containers (landing page)
As per our conversion today

**Status of the landing page:**
- [x] Navbar
- [x] First container
- [x] Second container
- [x] Third container (need minor fix but completed)
- [x] Fourth container
- [x] Footer

**Comment by EugeneGohh** [comment]
> @toreylittlefield Torey - the last 3 containers on landing page
> @EugeneGohh Eugene - navbar and the 2 containers (landing page)
> 
> As per our conversion today

Hey, just to give you an update. I am making the footer, I will make a new branch for it.

**Comment by EugeneGohh** [comment]
> > @toreylittlefield Torey - the last 3 containers on landing page
> > @EugeneGohh Eugene - navbar and the 2 containers (landing page)
> > As per our conversion today
> 
> Hey, just to give you an update. I am making the footer, I will make a new branch for it.

**Comment by EugeneGohh** [comment]
I am closing this issue now.
